/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['a.sort[_ngcontent-%COMP%] {\n\n  &.asc, &.desc {\n    font-weight: bold;\n\n    &::after {\n      content: \'\';\n      display: inline-block;\n      width: 0;\n      height: 0;\n      border-bottom: 4px solid rgba(0, 0, 0, 0.3);\n      border-top: 4px solid transparent;\n      border-left: 4px solid transparent;\n      border-right: 4px solid transparent;\n      margin-bottom: 2px;\n    }\n  }\n\n  &.desc::after {\n    transform: rotate(-180deg);\n    margin-bottom: -2px;\n  }\n}'];