/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../src/ng2-smart-table/components/cell/cell-edit-mode/default-edit.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../../../../src/ng2-smart-table/components/cell/cell-editors/select-editor.component';
import * as import10 from '../cell-editors/select-editor.component.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../../../../src/ng2-smart-table/components/cell/cell-editors/textarea-editor.component';
import * as import13 from '../cell-editors/textarea-editor.component.ngfactory';
import * as import14 from '../../../../../../src/ng2-smart-table/components/cell/cell-editors/checkbox-editor.component';
import * as import15 from '../cell-editors/checkbox-editor.component.ngfactory';
import * as import16 from '../../../../../../src/ng2-smart-table/components/cell/cell-editors/completer-editor.component';
import * as import17 from '../cell-editors/completer-editor.component.ngfactory';
import * as import18 from 'ng2-completer/services/completer-service';
import * as import19 from '../../../../../../src/ng2-smart-table/components/cell/cell-editors/input-editor.component';
import * as import20 from '../cell-editors/input-editor.component.ngfactory';
import * as import21 from '../../../../../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/common/src/directives/ng_switch';
export class Wrapper_DefaultEditComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DefaultEditComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.DefaultEditComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_cell(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.cell = currValue;
      this._expr_0 = currValue;
    }
  }
  check_inputClass(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.inputClass = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.edited.subscribe(_eventHandler.bind(view,'edited'))); }
  }
}
var renderType_DefaultEditComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_DefaultEditComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.DefaultEditComponent>;
  _DefaultEditComponent_0_3:Wrapper_DefaultEditComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DefaultEditComponent_Host0,renderType_DefaultEditComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'table-cell-default-editor',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_DefaultEditComponent0(this.viewUtils,this,0,this._el_0);
    this._DefaultEditComponent_0_3 = new Wrapper_DefaultEditComponent();
    this.compView_0.create(this._DefaultEditComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._DefaultEditComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DefaultEditComponent) && (0 === requestNodeIndex))) { return this._DefaultEditComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultEditComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._DefaultEditComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DefaultEditComponentNgFactory:import8.ComponentFactory<import0.DefaultEditComponent> = new import8.ComponentFactory<import0.DefaultEditComponent>('table-cell-default-editor',View_DefaultEditComponent_Host0,import0.DefaultEditComponent);
const styles_DefaultEditComponent:any[] = ([] as any[]);
class View_DefaultEditComponent1 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import9.SelectEditorComponent>;
  _SelectEditorComponent_0_3:import10.Wrapper_SelectEditorComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_DefaultEditComponent1,renderType_DefaultEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'select-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_SelectEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._SelectEditorComponent_0_3 = new import10.Wrapper_SelectEditorComponent();
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_0.create(this._SelectEditorComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'onClick',(null as any),'onEdited',(null as any),'onStopEditing',(null as any)),this.eventHandler(this.handleEvent_0));
    this._SelectEditorComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true,true,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.SelectEditorComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._SelectEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.cell;
    this._SelectEditorComponent_0_3.check_cell(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.inputClass;
    this._SelectEditorComponent_0_3.check_inputClass(currVal_0_0_1,throwOnChange,false);
    this._SelectEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._SelectEditorComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onClick')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onClick($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onEdited')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onEdited($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'onStopEditing')) {
      const pd_sub_2:any = ((<any>this.parentView.context.onStopEditing()) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}
class View_DefaultEditComponent2 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import12.TextareaEditorComponent>;
  _TextareaEditorComponent_0_3:import13.Wrapper_TextareaEditorComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_DefaultEditComponent2,renderType_DefaultEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'textarea-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import13.View_TextareaEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._TextareaEditorComponent_0_3 = new import13.Wrapper_TextareaEditorComponent();
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_0.create(this._TextareaEditorComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'onClick',(null as any),'onEdited',(null as any),'onStopEditing',(null as any)),this.eventHandler(this.handleEvent_0));
    this._TextareaEditorComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true,true,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TextareaEditorComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._TextareaEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.cell;
    this._TextareaEditorComponent_0_3.check_cell(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.inputClass;
    this._TextareaEditorComponent_0_3.check_inputClass(currVal_0_0_1,throwOnChange,false);
    this._TextareaEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._TextareaEditorComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onClick')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onClick($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onEdited')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onEdited($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'onStopEditing')) {
      const pd_sub_2:any = ((<any>this.parentView.context.onStopEditing()) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}
class View_DefaultEditComponent3 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import14.CheckboxEditorComponent>;
  _CheckboxEditorComponent_0_3:import15.Wrapper_CheckboxEditorComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_DefaultEditComponent3,renderType_DefaultEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'checkbox-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import15.View_CheckboxEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._CheckboxEditorComponent_0_3 = new import15.Wrapper_CheckboxEditorComponent();
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_0.create(this._CheckboxEditorComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'onClick',(null as any)),this.eventHandler(this.handleEvent_0));
    this._CheckboxEditorComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),false,false,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.CheckboxEditorComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CheckboxEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.cell;
    this._CheckboxEditorComponent_0_3.check_cell(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.inputClass;
    this._CheckboxEditorComponent_0_3.check_inputClass(currVal_0_0_1,throwOnChange,false);
    this._CheckboxEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CheckboxEditorComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onClick')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onClick($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_DefaultEditComponent4 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import16.CompleterEditorComponent>;
  _CompleterEditorComponent_0_3:import17.Wrapper_CompleterEditorComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_DefaultEditComponent4,renderType_DefaultEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'completer-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import17.View_CompleterEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._CompleterEditorComponent_0_3 = new import17.Wrapper_CompleterEditorComponent(this.parentView.parentView.injectorGet(import18.CompleterService,this.parentView.parentIndex));
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_0.create(this._CompleterEditorComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.CompleterEditorComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CompleterEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.cell;
    this._CompleterEditorComponent_0_3.check_cell(currVal_0_0_0,throwOnChange,false);
    this._CompleterEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CompleterEditorComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_DefaultEditComponent5 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import19.InputEditorComponent>;
  _InputEditorComponent_0_3:import20.Wrapper_InputEditorComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_DefaultEditComponent5,renderType_DefaultEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'input-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import20.View_InputEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._InputEditorComponent_0_3 = new import20.Wrapper_InputEditorComponent();
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_0.create(this._InputEditorComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'onClick',(null as any),'onEdited',(null as any),'onStopEditing',(null as any)),this.eventHandler(this.handleEvent_0));
    this._InputEditorComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true,true,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.InputEditorComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._InputEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.cell;
    this._InputEditorComponent_0_3.check_cell(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.inputClass;
    this._InputEditorComponent_0_3.check_inputClass(currVal_0_0_1,throwOnChange,false);
    this._InputEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._InputEditorComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onClick')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onClick($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onEdited')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onEdited($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'onStopEditing')) {
      const pd_sub_2:any = ((<any>this.parentView.context.onStopEditing()) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}
var renderType_DefaultEditComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_DefaultEditComponent,{});
export class View_DefaultEditComponent0 extends import2.AppView<import0.DefaultEditComponent> {
  _el_0:any;
  _NgSwitch_0_3:import21.Wrapper_NgSwitch;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgSwitchCase_2_6:import21.Wrapper_NgSwitchCase;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import11.ViewContainer;
  _TemplateRef_4_5:any;
  _NgSwitchCase_4_6:import21.Wrapper_NgSwitchCase;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import11.ViewContainer;
  _TemplateRef_6_5:any;
  _NgSwitchCase_6_6:import21.Wrapper_NgSwitchCase;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import11.ViewContainer;
  _TemplateRef_8_5:any;
  _NgSwitchCase_8_6:import21.Wrapper_NgSwitchCase;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _vc_10:import11.ViewContainer;
  _TemplateRef_10_5:any;
  _NgSwitchDefault_10_6:import21.Wrapper_NgSwitchDefault;
  _text_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DefaultEditComponent0,renderType_DefaultEditComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSwitch_0_3 = new import21.Wrapper_NgSwitch();
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import22.TemplateRef_(this,2,this._anchor_2);
    this._NgSwitchCase_2_6 = new import21.Wrapper_NgSwitchCase(this._vc_2.vcRef,this._TemplateRef_2_5,this._NgSwitch_0_3.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_4 = new import11.ViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import22.TemplateRef_(this,4,this._anchor_4);
    this._NgSwitchCase_4_6 = new import21.Wrapper_NgSwitchCase(this._vc_4.vcRef,this._TemplateRef_4_5,this._NgSwitch_0_3.context);
    this._text_5 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_6 = new import11.ViewContainer(6,0,this,this._anchor_6);
    this._TemplateRef_6_5 = new import22.TemplateRef_(this,6,this._anchor_6);
    this._NgSwitchCase_6_6 = new import21.Wrapper_NgSwitchCase(this._vc_6.vcRef,this._TemplateRef_6_5,this._NgSwitch_0_3.context);
    this._text_7 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_8 = new import11.ViewContainer(8,0,this,this._anchor_8);
    this._TemplateRef_8_5 = new import22.TemplateRef_(this,8,this._anchor_8);
    this._NgSwitchCase_8_6 = new import21.Wrapper_NgSwitchCase(this._vc_8.vcRef,this._TemplateRef_8_5,this._NgSwitch_0_3.context);
    this._text_9 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_10 = new import11.ViewContainer(10,0,this,this._anchor_10);
    this._TemplateRef_10_5 = new import22.TemplateRef_(this,10,this._anchor_10);
    this._NgSwitchDefault_10_6 = new import21.Wrapper_NgSwitchDefault(this._vc_10.vcRef,this._TemplateRef_10_5,this._NgSwitch_0_3.context);
    this._text_11 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._anchor_10,
      this._text_11
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import23.NgSwitchCase) && (2 === requestNodeIndex))) { return this._NgSwitchCase_2_6.context; }
    if (((token === import22.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import23.NgSwitchCase) && (4 === requestNodeIndex))) { return this._NgSwitchCase_4_6.context; }
    if (((token === import22.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import23.NgSwitchCase) && (6 === requestNodeIndex))) { return this._NgSwitchCase_6_6.context; }
    if (((token === import22.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import23.NgSwitchCase) && (8 === requestNodeIndex))) { return this._NgSwitchCase_8_6.context; }
    if (((token === import22.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import23.NgSwitchDefault) && (10 === requestNodeIndex))) { return this._NgSwitchDefault_10_6.context; }
    if (((token === import23.NgSwitch) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgSwitch_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.getEditorType();
    this._NgSwitch_0_3.check_ngSwitch(currVal_0_0_0,throwOnChange,false);
    this._NgSwitch_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = 'list';
    this._NgSwitchCase_2_6.check_ngSwitchCase(currVal_2_0_0,throwOnChange,false);
    this._NgSwitchCase_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:any = 'textarea';
    this._NgSwitchCase_4_6.check_ngSwitchCase(currVal_4_0_0,throwOnChange,false);
    this._NgSwitchCase_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    const currVal_6_0_0:any = 'checkbox';
    this._NgSwitchCase_6_6.check_ngSwitchCase(currVal_6_0_0,throwOnChange,false);
    this._NgSwitchCase_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    const currVal_8_0_0:any = 'completer';
    this._NgSwitchCase_8_6.check_ngSwitchCase(currVal_8_0_0,throwOnChange,false);
    this._NgSwitchCase_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    this._NgSwitchDefault_10_6.ngDoCheck(this,this._anchor_10,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this._vc_10.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
    this._vc_6.destroyNestedViews();
    this._vc_8.destroyNestedViews();
    this._vc_10.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 2)) { return new View_DefaultEditComponent1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_DefaultEditComponent2(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    if ((nodeIndex == 6)) { return new View_DefaultEditComponent3(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    if ((nodeIndex == 8)) { return new View_DefaultEditComponent4(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    if ((nodeIndex == 10)) { return new View_DefaultEditComponent5(this.viewUtils,this,10,this._anchor_10,this._vc_10); }
    return (null as any);
  }
}