/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../src/ng2-smart-table/components/cell/cell-edit-mode/edit-cell.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../../../../src/ng2-smart-table/components/cell/cell-edit-mode/custom-edit.component';
import * as import10 from './custom-edit.component.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/linker/component_factory_resolver';
import * as import13 from '../../../../../../src/ng2-smart-table/components/cell/cell-edit-mode/default-edit.component';
import * as import14 from './default-edit.component.ngfactory';
import * as import15 from '../../../../../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/common/src/directives/ng_switch';
export class Wrapper_EditCellComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EditCellComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.EditCellComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_cell(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.cell = currValue;
      this._expr_0 = currValue;
    }
  }
  check_inputClass(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.inputClass = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.edited.subscribe(_eventHandler.bind(view,'edited'))); }
  }
}
var renderType_EditCellComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_EditCellComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.EditCellComponent>;
  _EditCellComponent_0_3:Wrapper_EditCellComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EditCellComponent_Host0,renderType_EditCellComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'table-cell-edit-mode',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EditCellComponent0(this.viewUtils,this,0,this._el_0);
    this._EditCellComponent_0_3 = new Wrapper_EditCellComponent();
    this.compView_0.create(this._EditCellComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._EditCellComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EditCellComponent) && (0 === requestNodeIndex))) { return this._EditCellComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EditCellComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._EditCellComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EditCellComponentNgFactory:import8.ComponentFactory<import0.EditCellComponent> = new import8.ComponentFactory<import0.EditCellComponent>('table-cell-edit-mode',View_EditCellComponent_Host0,import0.EditCellComponent);
const styles_EditCellComponent:any[] = ([] as any[]);
class View_EditCellComponent1 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import9.CustomEditComponent>;
  _CustomEditComponent_0_3:import10.Wrapper_CustomEditComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_EditCellComponent1,renderType_EditCellComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'table-cell-custom-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_CustomEditComponent0(this.viewUtils,this,0,this._el_0);
    this._CustomEditComponent_0_3 = new import10.Wrapper_CustomEditComponent(this.parentView.parentView.injectorGet(import12.ComponentFactoryResolver,this.parentView.parentIndex));
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_0.create(this._CustomEditComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'edited',(null as any)),this.eventHandler(this.handleEvent_0));
    this._CustomEditComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.CustomEditComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CustomEditComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.cell;
    this._CustomEditComponent_0_3.check_cell(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.inputClass;
    this._CustomEditComponent_0_3.check_inputClass(currVal_0_0_1,throwOnChange,false);
    this._CustomEditComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CustomEditComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'edited')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onEdited($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_EditCellComponent2 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import13.DefaultEditComponent>;
  _DefaultEditComponent_0_3:import14.Wrapper_DefaultEditComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_EditCellComponent2,renderType_EditCellComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'table-cell-default-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import14.View_DefaultEditComponent0(this.viewUtils,this,0,this._el_0);
    this._DefaultEditComponent_0_3 = new import14.Wrapper_DefaultEditComponent();
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_0.create(this._DefaultEditComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'edited',(null as any)),this.eventHandler(this.handleEvent_0));
    this._DefaultEditComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.DefaultEditComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._DefaultEditComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.cell;
    this._DefaultEditComponent_0_3.check_cell(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.inputClass;
    this._DefaultEditComponent_0_3.check_inputClass(currVal_0_0_1,throwOnChange,false);
    this._DefaultEditComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._DefaultEditComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'edited')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onEdited($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_EditCellComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_EditCellComponent,{});
export class View_EditCellComponent0 extends import2.AppView<import0.EditCellComponent> {
  _text_0:any;
  _el_1:any;
  _NgSwitch_1_3:import15.Wrapper_NgSwitch;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _vc_3:import11.ViewContainer;
  _TemplateRef_3_5:any;
  _NgSwitchCase_3_6:import15.Wrapper_NgSwitchCase;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import11.ViewContainer;
  _TemplateRef_5_5:any;
  _NgSwitchDefault_5_6:import15.Wrapper_NgSwitchDefault;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EditCellComponent0,renderType_EditCellComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n      ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSwitch_1_3 = new import15.Wrapper_NgSwitch();
    this._text_2 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._vc_3 = new import11.ViewContainer(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import16.TemplateRef_(this,3,this._anchor_3);
    this._NgSwitchCase_3_6 = new import15.Wrapper_NgSwitchCase(this._vc_3.vcRef,this._TemplateRef_3_5,this._NgSwitch_1_3.context);
    this._text_4 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._vc_5 = new import11.ViewContainer(5,1,this,this._anchor_5);
    this._TemplateRef_5_5 = new import16.TemplateRef_(this,5,this._anchor_5);
    this._NgSwitchDefault_5_6 = new import15.Wrapper_NgSwitchDefault(this._vc_5.vcRef,this._TemplateRef_5_5,this._NgSwitch_1_3.context);
    this._text_6 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import17.NgSwitchCase) && (3 === requestNodeIndex))) { return this._NgSwitchCase_3_6.context; }
    if (((token === import16.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import17.NgSwitchDefault) && (5 === requestNodeIndex))) { return this._NgSwitchDefault_5_6.context; }
    if (((token === import17.NgSwitch) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._NgSwitch_1_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.getEditorType();
    this._NgSwitch_1_3.check_ngSwitch(currVal_1_0_0,throwOnChange,false);
    this._NgSwitch_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    const currVal_3_0_0:any = 'custom';
    this._NgSwitchCase_3_6.check_ngSwitchCase(currVal_3_0_0,throwOnChange,false);
    this._NgSwitchCase_3_6.ngDoCheck(this,this._anchor_3,throwOnChange);
    this._NgSwitchDefault_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    this._vc_3.detectChangesInNestedViews(throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_3.destroyNestedViews();
    this._vc_5.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 3)) { return new View_EditCellComponent1(this.viewUtils,this,3,this._anchor_3,this._vc_3); }
    if ((nodeIndex == 5)) { return new View_EditCellComponent2(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    return (null as any);
  }
}