/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../src/ng2-smart-table/components/cell/cell-editors/textarea-editor.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './editor.component.scss.shim.ngstyle';
import * as import10 from '../../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import11 from '../../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import12 from '../../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import13 from '../../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import14 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import15 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/common/src/directives/ng_class';
import * as import18 from '@angular/forms/src/directives/default_value_accessor';
import * as import19 from '@angular/forms/src/directives/control_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control';
import * as import22 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_TextareaEditorComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TextareaEditorComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  constructor() {
    this._changed = false;
    this.context = new import0.TextareaEditorComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
  }
  check_cell(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.cell = currValue;
      this._expr_0 = currValue;
    }
  }
  check_inputClass(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.inputClass = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.onStopEditing.subscribe(_eventHandler.bind(view,'onStopEditing'))); }
    if (emit1) { (this.subscription1 = this.context.onEdited.subscribe(_eventHandler.bind(view,'onEdited'))); }
    if (emit2) { (this.subscription2 = this.context.onClick.subscribe(_eventHandler.bind(view,'onClick'))); }
  }
}
var renderType_TextareaEditorComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_TextareaEditorComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.TextareaEditorComponent>;
  _TextareaEditorComponent_0_3:Wrapper_TextareaEditorComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TextareaEditorComponent_Host0,renderType_TextareaEditorComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'textarea-editor',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TextareaEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._TextareaEditorComponent_0_3 = new Wrapper_TextareaEditorComponent();
    this.compView_0.create(this._TextareaEditorComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._TextareaEditorComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TextareaEditorComponent) && (0 === requestNodeIndex))) { return this._TextareaEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TextareaEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._TextareaEditorComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TextareaEditorComponentNgFactory:import8.ComponentFactory<import0.TextareaEditorComponent> = new import8.ComponentFactory<import0.TextareaEditorComponent>('textarea-editor',View_TextareaEditorComponent_Host0,import0.TextareaEditorComponent);
const styles_TextareaEditorComponent:any[] = [import9.styles];
var renderType_TextareaEditorComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_TextareaEditorComponent,{});
export class View_TextareaEditorComponent0 extends import2.AppView<import0.TextareaEditorComponent> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import10.Wrapper_NgClass;
  _DefaultValueAccessor_1_4:import11.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_1_5:any[];
  _NgModel_1_6:import12.Wrapper_NgModel;
  _NgControl_1_7:any;
  _NgControlStatus_1_8:import13.Wrapper_NgControlStatus;
  _text_2:any;
  _text_3:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TextareaEditorComponent0,renderType_TextareaEditorComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_10 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'textarea',new import3.InlineArray2(2,'class','form-control'),(null as any));
    this._NgClass_1_3 = new import10.Wrapper_NgClass(this.parentView.injectorGet(import14.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import15.KeyValueDiffers,this.parentIndex),new import16.ElementRef(this._el_1),this.renderer);
    this._DefaultValueAccessor_1_4 = new import11.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_1));
    this._NG_VALUE_ACCESSOR_1_5 = [this._DefaultValueAccessor_1_4.context];
    this._NgModel_1_6 = new import12.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_1_5);
    this._NgControl_1_7 = this._NgModel_1_6.context;
    this._NgControlStatus_1_8 = new import13.Wrapper_NgControlStatus(this._NgControl_1_7);
    this._text_2 = this.renderer.createText(this._el_1,'    ',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray16(12,'ngModelChange',(null as any),'click',(null as any),'keydown.enter',(null as any),'keydown.esc',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_1));
    this._NgModel_1_6.subscribe(this,this.eventHandler(this.handleEvent_1),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._NgClass_1_3.context; }
    if (((token === import18.DefaultValueAccessor) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._DefaultValueAccessor_1_4.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._NG_VALUE_ACCESSOR_1_5; }
    if (((token === import20.NgModel) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._NgModel_1_6.context; }
    if (((token === import21.NgControl) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._NgControl_1_7; }
    if (((token === import22.NgControlStatus) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._NgControlStatus_1_8.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = 'form-control';
    this._NgClass_1_3.check_klass(currVal_1_0_0,throwOnChange,false);
    const currVal_1_0_1:any = this.context.inputClass;
    this._NgClass_1_3.check_ngClass(currVal_1_0_1,throwOnChange,false);
    this._NgClass_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    this._DefaultValueAccessor_1_4.ngDoCheck(this,this._el_1,throwOnChange);
    const currVal_1_2_0:any = this.context.cell.getId();
    this._NgModel_1_6.check_name(currVal_1_2_0,throwOnChange,false);
    const currVal_1_2_1:boolean = !this.context.cell.isEditable();
    this._NgModel_1_6.check_isDisabled(currVal_1_2_1,throwOnChange,false);
    const currVal_1_2_2:any = this.context.cell.newValue;
    this._NgModel_1_6.check_model(currVal_1_2_2,throwOnChange,false);
    this._NgModel_1_6.ngDoCheck(this,this._el_1,throwOnChange);
    this._NgControlStatus_1_8.ngDoCheck(this,this._el_1,throwOnChange);
    const currVal_10:any = this.context.cell.getTitle();
    if (import3.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_1,'placeholder',currVal_10);
      this._expr_10 = currVal_10;
    }
    this._NgControlStatus_1_8.checkHost(this,this,this._el_1,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_1_6.ngOnDestroy();
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_1_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.cell.newValue = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'click')) {
      const pd_sub_1:any = ((<any>this.context.onClick.emit($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'keydown.enter')) {
      const pd_sub_2:any = ((<any>this.context.onEdited.emit($event)) !== false);
      result = (pd_sub_2 && result);
    }
    if ((eventName == 'keydown.esc')) {
      const pd_sub_3:any = ((<any>this.context.onStopEditing.emit()) !== false);
      result = (pd_sub_3 && result);
    }
    return result;
  }
}