/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.ng2-smart-filter[_ngcontent-%COMP%] {\n  input {\n    width: 100%;\n    line-height: normal;\n    padding: .375rem .75rem;\n    font-weight: normal;\n  }\n}'];