/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.ng2-smart-table[_ngcontent-%COMP%] {\n  font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n  font-size: 16px;\n  line-height: 1.5;\n  color: #606c71;\n  border-collapse: collapse;\n  border-spacing: 0;\n  display: table;\n  width: 100%;\n  max-width: 100%;\n  overflow: auto;\n  word-break: normal;\n  word-break: keep-all;\n\n  td, th {\n    font-size: .875rem;\n    margin: 0;\n    padding: 0.5rem 1rem;\n    border: 1px solid #e9ebec;\n  }\n\n  .ng2-smart-row {\n    &.selected {\n      background: rgba(0, 0, 0, 0.05);\n    }\n\n    .ng2-smart-actions {\n      &.ng2-smart-action-multiple-select {\n        text-align: center;\n      }\n    }\n  }\n}'];