/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.ng2-smart-pagination[_ngcontent-%COMP%] {\n  display: inline-block;\n  font-size: .875rem;\n  padding: 0;\n  \n  .sr-only {\n    position: absolute;\n    width: 1px;\n    height: 1px;\n    padding: 0;\n    margin: -1px;\n    overflow: hidden;\n    clip: rect(0,0,0,0);\n    border: 0;\n  }\n  \n  .ng2-smart-page-item {\n    display: inline;\n  }\n}'];